import localFont from "next/font/local";
// import { Roboto } from `next/font/google`;
import Footer from "./components/footer";
import "./globals.css";

// const roboto = Roboto({
//   weight: `400`,
//   subsets: ['latin']
// })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Warung Hati",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header></header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
